2019-10-26 09:16:48,826 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-26 09:18:15,453 ERROR: Exception on /edit_profile [POST] [in /home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/leonid/hlam/microblog/app/routes.py", line 82, in edit_profile
    db.session.commit()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'Я живу как хочу, а ты нет!', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-10-26 09:29:41,845 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 02:45:54,241 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 06:53:45,996 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 06:54:22,908 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:05:15,866 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:05:49,519 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:08:15,913 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:10:21,591 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:11:20,873 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:11:58,812 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:13:55,796 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:15:44,712 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:15:52,297 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:53:48,276 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 08:56:01,080 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:21:33,795 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:25:12,906 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:30:49,463 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:31:40,122 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:40:13,360 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:48:38,459 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-28 09:58:51,403 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:02:14,920 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:04:27,747 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:04:40,962 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:21:18,637 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:22:25,836 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:26:21,311 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:39:32,909 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:40:51,722 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:47:24,908 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 02:53:28,188 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 03:50:49,205 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 06:27:03,664 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 06:47:51,286 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 06:48:15,280 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 06:57:04,928 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:02:50,123 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:03:52,518 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:05:02,858 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:06:31,235 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:08:34,075 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:09:56,169 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:21:14,947 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:25:54,062 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
